name: My First Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Inastall node_modules
        run: npm install
      - name: build the project
        run: npm build
      - name: deploying the project
        env: 
          VERCEL_ORD_ID: Wz1QBSDH1tydbCR3ATcUK4Ow
          POJECT_ID: prj_PWDhfRV2AxpJgiLtKlnX73hyLQXQ
        run: npm deploy
        - name: Setup Finish
        run: echo "hurryy!"


# name: My First Github Action
# on: [push]
# jobs:
#   build-app:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: tree