name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  buildApp:
    runs-on: ubuntu-latest
    outputs: 
      text: ${{ steps.finishedId.outputs.text }}
    env: 
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # It's better to use the latest LTS(Long term support) version.

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploying the project to Vercel
        run: npm run deploy

      - name: Setup Finish buildApp JOB
        run: echo "Deployment successful! =>  $VERCEL_TOKEN"

      - name: After Finish buildApp JOB
        id: finishedId
        run: echo "::set-output name=text::hello-world-from-buildApp-job" # varible ;text' read by other job like testApp and other
    
    testApp:
      runs-on: ubuntu-latest
      env: 
        BUILD_jOB_OUTPUT: ${{ needs.buildApp.outputs.text }}

      steps: 
        - run: echo "2nd dependent job with varible sharing named BUILD_jOB_OUTPUT=> $BUILD_jOB_OUTPUT, testApp job will execute after buildApp succesfully executes"