name: My First Github Action
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World !!!!!"
      - run: echo "This is step number 2"
  print-hello-world2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World 2 !!!!!"
      - run: echo "This is step number 2 2"